import Head from 'next/head'
import { AppProps } from 'next/dist/shared/lib/router/router'
import '../styles/globals.css'

function MyApp({ Component, pageProps, router }: AppProps): JSX.Element {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta name='og:urk' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
      <meta name='og:locale' content='ru_RU' />
      <meta name='og:type' content='article' />
    </Head>
    <Component {...pageProps} />
  </>;
}

export default MyApp;
