import Head from 'next/head';
import { AppProps } from 'next/dist/shared/lib/router/router';
import '../styles/globals.css';
import ym from 'react-yandex-metrika';
import { YMInitializer } from 'react-yandex-metrika';
import Router from 'next/router';

Router.events.on('routeChangeComplete', (url: string) => {
  if (typeof window != undefined) {
    ym('hit', url)
  }
});

function MyApp({ Component, pageProps, router }: AppProps): JSX.Element {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel='preconnect' href='htps://mc.yandex.ru' />
      <meta name='og:urk' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
      <meta name='og:locale' content='ru_RU' />
      <meta name='og:type' content='article' />
    </Head>
    <YMInitializer
      accounts={[]}
      options={{ webvisor: true, defer: true }}
      version='2'
    />
    <Component {...pageProps} />
  </>;
}

export default MyApp;
